FROM python:3.9-slim
WORKDIR /app
# Criando um index.html simples para o servidor servir
RUN echo "Bem-vindo ao Servidor Python Simples (Desafio 1)" > index.html
CMD ["python", "-m", "http.server", "8080"]
